# Example/Documentation for the IG YML file
# https://fshschool.org/docs/sushi/configuration/#exhaustive-example

# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: ch.fhir.ig.ch-epr-data-oe

canonical: http://fhir.ch/ig/ch-epr-data-oe
name: CH-EPR-DATA
title: "CH EPR DATA (R4)"
description: EPR Data
status: draft
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CHE
date: 2024-12-27
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2024+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: Oliver Egger
contact:
  - name: ahdis ag
    telecom:
      - system: url
        value: https://www.hl7.ch/

dependencies:
  hl7.terminology: 6.1.0
  ch.fhir.ig.ch-vacd: 5.0.0

pages:
  index.md:
    title: Home
  vacd.md:
    title: Vaccination

menu:
  Home: index.html
  Vaccination: vacd.html
  Artifacts: artifacts.html

# Parameters
# Core FHIR: http://build.fhir.org/codesystem-guide-parameter-code.html
# FHIR Tools IG: http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  allow-extensible-warnings: true
  display-warnings: true 
  path-resource:
    - input/resources
    - input/mappings

resources:
  Bundle/2021-06-22-Vaccination-Spikevax-Impfmodul:
    name: 2021-06-22-Vaccination-Spikevax-Impfmodul
    description: Vaccination Administration documented with EPR Vaccination module
    exampleBoolean: true
  Bundle/2021-06-22-Vaccination-Spikevax-Impfmodul-corrected:
    name: 2021-06-22-Vaccination-Spikevax-Impfmodul-corrected
    description: Vaccination Administration documented with EPR Vaccination module corrected with mapping script
    exampleBoolean: true
  Bundle/2021-12-21-Vaccination-Spikevax-Impfmodul:
    name: 2021-12-21-Vaccination-Spikevax-Impfmodul
    description: Vaccination Administration documented with EPR Vaccination module
    exampleBoolean: true
  Bundle/2021-12-21-Vaccination-Spikevax-Impfmodul-corrected:
    name: 2021-12-21-Vaccination-Spikevax-Impfmodul-corrected
    description: Vaccination Administration documented with EPR Vaccination module corrected with mapping script
    exampleBoolean: true
  Bundle/2024-06-16-FSME:
    name: 2024-06-16-FSME
    description: Vaccination Administration documented with EPR Vaccination module
    exampleBoolean: true
  Bundle/2024-06-16-FSME-corrected:
    name: 2024-06-16-FSME-corrected
    description: Vaccination Administration documented with EPR Vaccination module
    exampleBoolean: true
  Bundle/2024-06-24-emedo:
    name: 2024-06-24-emedo
    description: Vaccination Administration provided by emedo (original data from meineimpfungen.ch)
    exampleBoolean: true
  Bundle/2024-06-24-emedo-removed-duplicates:
    name: 2024-06-24-emedo-removed-duplicates
    description: Removed duplicates from emedo report
    exampleBoolean: true
  Bundle/2024-06-24-emedo-corrected:
    name: 2024-06-24-emedo-corrected
    description: Vaccination Administration documented with EPR Vaccination module corrected with mapping script
    exampleBoolean: true
  Bundle/2024-12-13-FluarixTextra:
    name: 2024-12-13-FluarixTextra
    description: Vaccination Administration documented with EPR Vaccination module
    exampleBoolean: true
  Bundle/2024-12-13-FluarixTetra-corrected:
    name: 2024-12-13-FluarixTetra-corrected
    description: Vaccination Administration documented with EPR Vaccination module corrected with mapping script
    exampleBoolean: true
  StructureMap/AdaptImmunizationAdministration:
    name: AdaptImmunizationAdministration
    description: Adaptes Immunization Administration that it validates against CH VACD for eHS Vaccination Module and emedo export
  